backend:
  name: git-gateway
  branch: main

media_folder: src/assets/images/
public_folder: src/assets/images/

collections:
  - name: "cars"
    label: "Car Inventory"
    folder: "src/content/cars"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          hint: "URL slug (e.g. toyota-corolla-2022)",
          required: true,
        }
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Short Description",
          name: "short_description",
          widget: "text",
          required: true,
        }
      - {
          label: "Featured Image",
          name: "featured_image",
          widget: "image",
          required: true,
        }
      - {
          label: "Content",
          name: "content",
          widget: "markdown",
          required: true,
        }
      - { label: "Price", name: "price", widget: "string", required: false }
      - {
          label: "Phone Number",
          name: "phone_number",
          widget: "string",
          required: true,
        }
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        field:
          { label: "Image", name: "image", widget: "image", required: true }
      - label: "Attributes"
        name: "attributes"
        widget: "list"
        fields:
          - {
              label: "Attribute Name",
              name: "name",
              widget: "select",
              options: ["Transmission", "Fuel Type", "Year", "Mileage"],
            }
          - { label: "Value", name: "value", widget: "string", required: true }
          - {
              label: "Featured",
              name: "featured",
              widget: "boolean",
              default: false,
              hint: "Check this to feature this attribute on the car card.",
            }
      - label: "Additional Details"
        name: "additional_details"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - {
              label: "Description",
              name: "description",
              widget: "markdown",
              required: true,
            }
      - label: "SEO"
        name: "seo"
        widget: "object"
        fields:
          - {
              label: "SEO Title",
              name: "seo_title",
              widget: "string",
              required: false,
            }
          - {
              label: "SEO Description",
              name: "seo_description",
              widget: "text",
              required: false,
            }

  - name: "contacts"
    label: "Contact Info"
    create: false
    files:
      - name: "dealerships"
        label: "Dealerships"
        file: "src/content/contacts/dealerships.md"
        fields:
          - label: "Locations"
            name: "locations"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Address", name: "address", widget: "string" }
              - { label: "Phone", name: "phone", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
              - { label: "Hours", name: "hours", widget: "string" }
